// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQXEloq45V55xWcVhKGov6s27ffRPM0c',
    appId: '1:291127447179:web:198eb4922b25e807204e8e',
    messagingSenderId: '291127447179',
    projectId: 'chat-app-43034',
    authDomain: 'chat-app-43034.firebaseapp.com',
    storageBucket: 'chat-app-43034.appspot.com',
    measurementId: 'G-B2NEYR0H5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEnQ9EvcWDyUgF2O7vVQHS49xHgjHYems',
    appId: '1:291127447179:android:3f80542147d1e676204e8e',
    messagingSenderId: '291127447179',
    projectId: 'chat-app-43034',
    storageBucket: 'chat-app-43034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB97FHqCiThTxqXAXrBqBFcndVCXPKltx4',
    appId: '1:291127447179:ios:d617e1a3ec282533204e8e',
    messagingSenderId: '291127447179',
    projectId: 'chat-app-43034',
    storageBucket: 'chat-app-43034.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB97FHqCiThTxqXAXrBqBFcndVCXPKltx4',
    appId: '1:291127447179:ios:d617e1a3ec282533204e8e',
    messagingSenderId: '291127447179',
    projectId: 'chat-app-43034',
    storageBucket: 'chat-app-43034.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoQXEloq45V55xWcVhKGov6s27ffRPM0c',
    appId: '1:291127447179:web:7e50b3ead963d342204e8e',
    messagingSenderId: '291127447179',
    projectId: 'chat-app-43034',
    authDomain: 'chat-app-43034.firebaseapp.com',
    storageBucket: 'chat-app-43034.appspot.com',
    measurementId: 'G-LZGSEV11K5',
  );

}